# -*- coding: utf-8 -*-
"""
/***************************************************************************
 criar_pontos_rios
                                 A QGIS plugin
 Cria pontos de inicio, fim e confluentes dos Rios.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-15
        copyright            : (C) 2020 by Antônio Teles
        email                : antoniot.leandro@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load criar_pontos_rios class from file criar_pontos_rios.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CriarPontosRios import criar_pontos_rios
    return criar_pontos_rios(iface)
